language: c
#os: windows

os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc

sudo: false
script:
  - rm -rf build_result
  - mkdir -p build_result
  - make install PREFIX=build_result CC=$CC DOXYGEN=
