language: c
#os: windows

#os:
#  - linux
#  - osx
#  
#compiler:
#  - clang
#  - gcc

jobs:
  include:
#    - name: "Linux GCC"
#      os: linux
#      compiler: gcc
#    - name: "Linux Clang"
#      os: linux
#      compiler: clang
#    - name: "Mac OS X Clang"
#      os: osx
#      compiler: clang
    - name: "Win32 GCC"
      os: windows
      env: WINBITS=32
      compiler: gcc
#    - name: "Win64 GCC"
#      os: windows
#      env: WINBITS=64
#      compiler: gcc
#
#before_install:
#- |-
#    case $TRAVIS_OS_NAME in
#      windows)
#        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
#        choco uninstall -y mingw
#        choco upgrade --no-progress -y msys2
#        export msys2='cmd //C RefreshEnv.cmd '
#        export msys2+='& set MSYS=winsymlinks:nativestrict '
#        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
#        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
#        export msys2+=" -msys2 -c "\"\$@"\" --"
#        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
#        ## Install more MSYS2 packages from https://packages.msys2.org/base here
#        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
#        export PATH=/C/tools/msys64/mingw64/bin:$PATH
#        ;;
#    esac
#
#before_cache:
#- |-
#    case $TRAVIS_OS_NAME in
#      windows)
#        # https://unix.stackexchange.com/a/137322/107554
#        $msys2 pacman --sync --clean --noconfirm
#        ;;
#    esac
#
#cache:
#    directories:
#    - $HOME/AppData/Local/Temp/chocolatey
#    - /C/tools/msys64

before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        if [ ! -f "C:/Prog/msys64/installed" ]; then
          wget -qc -P"C:/Prog" http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20190524.tar.xz
          mkdir -p "C:/Prog"
          "C:/Program Files/7-Zip/7z.exe" e -so msys2-base-x86_64-20190524.tar.xz | tar x -C "C:/Prog"
          rm -f C:/Prog/msys2-base-*.tar.xz
          ls -l "C:/Prog/msys64"
          #touch "C:/Prog/msys64/base-dlls.txt" "C:/Prog/msys64/base-dlls-unix.txt"
          cd C:/Prog/msys64 && ( cmd.exe "//C" "autorebasebase1st.bat" || cmd.exe "//C" "autorebase.bat" )
          touch "C:/Prog/msys64/installed"
          echo "Please reboot Windows before proceeding"
          travis_terminate 1
        fi
        ;;
    esac

cache:
    - /C/Prog
    
sudo: false
script:
  - rm -rf build_result
  - mkdir -p build_result
  - make install PREFIX=build_result CC=$CC DOXYGEN=
