version: 1.0.{build}
max_jobs: 1
image: "Windows Server 2012 R2"

init:
  - pwd
  - ls
  - ls C:/MinGW/msys/1.0
  - ls C:/MinGW/msys/1.0/bin

build_script:
  - mkdir -p build_result
  - make install PREFIX=build_result CC=$CC DOXYGEN=
