version: 1.0.{build}
max_jobs: 1
image: "Windows Server 2012 R2"

init:
  - pwd
  - ls
  - ls 'C:\msys64'
  - ls C:/msys64/

build_script:
  - mkdir -p build_result
  - make install PREFIX=build_result CC=$CC DOXYGEN=
