version: 1.0.{build}
max_jobs: 1
image: "Windows Server 2012 R2"

init:
  - SET PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin;C:/msys64/usr/bin;%PATH%

build_script:
  - gcc --version
  - ls -l
  - mkdir -p build_result
  - make install PREFIX=build_result DOXYGEN= V=1
