name: GitHub-CI for ci-test
#name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  build:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2
#    - name: Run a multi-line script
#      run: |
#        make --version
#        gcc --version
#        mkdir -p build_result
#        make install PREFIX=build_result DOXYGEN=
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "winlibs 32-bit", artifact: "win32-winlibs.tar.bz2",
            os: windows-latest,
            cc: "gcc.exe", cxx: "g++.exe",
            configure_method: "", build_method: "make"
          }
        - {
            name: "Windows MinGW (make)", artifact: "win64-MinGW.tar.bz2",
            os: windows-latest,
            cc: "x86_64-w64-mingw32-gcc.exe", cxx: "x86_64-w64-mingw32-g++.exe",
            configure_method: "", build_method: "make"
          }
        - {
            name: "Ubuntu GCC (make)", artifact: "linux.tar.bz2",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++",
            configure_method: "", build_method: "make"
          }
        - {
            name: "macOS Clang (make)", artifact: "macos.tar.bz2",
            os: macos-latest,
            cc: "clang", cxx: "clang++",
            configure_method: "", build_method: "make"
          }
        - {
            name: "Ubuntu GCC (cmake+make)", artifact: "linux-cmake.tar.bz2",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++",
            configure_method: "cmake", build_method: "make", cmake_generator: "Unix Makefiles"
          }
#        - {
#            name: "Windows 32-bit MinGW (cmake+make)", artifact: "win32-MinGW-cmake.tar.bz2",
#            os: windows-latest,
#            cc: "i686-w64-mingw32-gcc.exe", cxx: "i686-w64-mingw32-g++.exe",
#            configure_method: "cmake", build_method: "make", cmake_generator: "MSYS Makefiles"
#          }
        - {
            name: "Windows 64-bit MinGW (cmake+make)", artifact: "win64-MinGW-cmake.tar.bz2",
            os: windows-latest,
            cc: "x86_64-w64-mingw32-gcc.exe", cxx: "x86_64-w64-mingw32-g++.exe",
            configure_method: "cmake", build_method: "make", cmake_generator: "MSYS Makefiles"
          }
        - {
            name: "Windows 32-bit MSVC (cmake)", artifact: "win32-MSVC-cmake.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl", arch: "x86",
#            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            configure_method: "cmake", build_method: "nmake", cmake_generator: "NMake Makefiles"
          }
        - {
            name: "Windows 64-bit MSVC (cmake)", artifact: "win64-MSVC-cmake.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl", arch: "amd64",
#            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            configure_method: "cmake", build_method: "nmake", cmake_generator: "NMake Makefiles"
          }
    steps:
    - uses: actions/checkout@v1
#    - if: matrix.config.environment_script != ''
#      name: Environment script
#      run: |
#        "${{ matrix.config.environment_script }}"
    - if: contains( matrix.config.name, 'winlibs' )
      name: Install winlibs
      run: |
        7z --help
        curl --help
    - if: matrix.config.cc == 'cl'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.config.arch }}
    - if: matrix.config.configure_method != 'cmake'
      name: Configure
      run: |
        echo "::set-env name=MAKEDIR::."
    - if: matrix.config.configure_method == 'cmake'
      name: Configure (CMake)
      run: |
        cmake -G"${{ matrix.config.cmake_generator }}" -DCMAKE_CC_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_INSTALL_PREFIX:PATH=../build_result -DBUILD_STATIC:BOOL=ON -DBUILD_SHARED:BOOL=ON -DBUILD_UTILS:BOOL=ON -DBUILD_DOCUMENTATION:BOOL=OFF -S. -Bbuild_temp
        echo "::set-env name=MAKEDIR::build_temp"
    - if: matrix.config.build_method == 'make'
      name: Build + install (make)
      run: |
        make -C${{ env.MAKEDIR }} install PREFIX=build_result DOXYGEN= CC=${{ matrix.config.cc }}
    - if: matrix.config.build_method == 'nmake'
      name: Build + install (nmake)
      run: |
        #cmake --build ${{ env.MAKEDIR }}
        #cmake --install ${{ env.MAKEDIR }}
        pushd ${{ env.MAKEDIR }}
        nmake /NOLOGO install
        popd
    - name: Pack
      run: |
        tar cfj ./${{ matrix.config.artifact }} --strip-components=1 build_result
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: ./${{ matrix.config.artifact }}
        name: ${{ matrix.config.artifact }}
