name: Manually triggered workflow 2
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    needs: Manually triggered workflow 1
    steps:
    - run: |
        echo "Workflow 2 - depends on 1"
