name: winlibs test

on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "winlibs 32-bit", artifact: "win32-winlibs.tar.bz2",
            os: windows-latest,
            cc: "gcc.exe", cxx: "g++.exe", winlibs_bits: "32", winlibs_url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.1.1-snapshot20200704-7.0.0/winlibs-i686-posix-dwarf-gcc-10.1.1-snapshot20200704-mingw-w64-7.0.0-r1.7z",
          }
        - {
            name: "winlibs 64-bit", artifact: "win64-winlibs.tar.bz2",
            os: windows-latest,
            cc: "gcc.exe", cxx: "g++.exe", winlibs_bits: "64", winlibs_url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/10.1.1-snapshot20200704-7.0.0/winlibs-x86_64-posix-seh-gcc-10.1.1-snapshot20200704-mingw-w64-7.0.0-r1.7z",
          }
    steps:
    - if: contains( matrix.config.name, 'winlibs' )
      name: Install winlibs
      run: |
        curl -k -L -# -o winlibs.7z ${{ matrix.config.winlibs_url }}
        7z x -y -bd -oD:\Prog\winlibs winlibs.7z
        Remove-Item winlibs.7z
        echo "::add-path::D:\Prog\winlibs\mingw${{ matrix.config.winlibs_bits }}\bin"
    - name: Test
      run: |
        gcc --version
